### ISSUE TITLE
Per-person <author> element in package.xml

### ISSUE THREAD

**Issue by scymtym** [ubi-agni/agni_robots#1]
[agni_description/package.xml](../tree/kinetic-devel/agni_description/package.xml#L10) contains ``<author>Guillaume Walck, Robert Haschke</author>``. Two ``<author>`` elements would be better for machine-readability.

**Comment by guihomework** [comment]
Done in https://github.com/ubi-agni/agni_robots/commit/40c9d5a1bd7a7372d478a2da13db3c444cfc5ffb . Now following rules as in http://ros.org/reps/rep-0127.html#author-multiple
